In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_colwidth', 400)

## Data loading
---
In order to perform data analysis on annotated dataset just download whole dataset form Google Drive, select only annotated rows and save it as .csv. Then perform infos and annotations merge by new indices.

In [3]:
df_infos = pd.read_csv('data/sady_main/sady_infos_raw.csv')
df_infos.head(2)

/home/jakub/Dokumenty/venv36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest,new_id
0,"4,74999593189773E+017","4,74982910425301E+017",1402083702000,2014-06-06,21:41:42,CEST,2367137142,krzysztofcicho3,Krzysztof Cichosz,NaN,...,NaN,NaN,NaN,NaN,"[{'user_id': '2367137142', 'username': 'KrzysztofCicho3'}, {'user_id': '244246777', 'username': 'TomSokolewicz'}]",NaN,NaN,NaN,NaN,0
1,"4,74958618094105E+017","4,74958618094105E+017",1402073933000,2014-06-06,18:58:53,CEST,780543464,zalewski53,Roland Zalewski,NaN,...,NaN,NaN,NaN,NaN,"[{'user_id': '780543464', 'username': 'Zalewski53'}]",NaN,NaN,NaN,NaN,1

In [4]:
df_infos.columns

Index(['id', 'conversation_id', 'created_at', 'date', 'time', 'timezone',
       'user_id', 'username', 'name', 'place', 'tweet', 'mentions', 'urls',
       'photos', 'replies_count', 'retweets_count', 'likes_count', 'hashtags',
       'cashtags', 'link', 'retweet', 'quote_url', 'video', 'near', 'geo',
       'source', 'user_rt_id', 'user_rt', 'retweet_id', 'reply_to',
       'retweet_date', 'translate', 'trans_src', 'trans_dest', 'new_id'],
      dtype='object')

In [5]:
df_annotated = pd.read_csv('data/sady_main/sady_date_annotated.csv', sep='\t')
df_annotated = df_annotated.drop(columns=['date', 'time'])
df_annotated.head(2)

,id,tekst,wydźwięk,klucze,wyzywanie,grożenie,wykluczanie,odczłowieczanie,poniżanie,stygmatyzacja,szantaż,inne,ksenofobia,szowinizm,rasizm,seksizm,antysemityzm,homofobia,inne.1
0,9,w czwartek muszę poprawić sądy i trybunały,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8,"Żale Nałęcza i riposta Macierewicza: Pan był w kompartii, czy ma prawo wy­gła­szać takie sądy? | niezalezna.pl …",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Get only useful data from infos dataframe.

In [6]:
df_infos = df_infos[['new_id', 'date', 'time']]  # and maybe other ... later
df_infos = df_infos.dropna()
df_infos['new_id'] = df_infos['new_id'].astype(int)
df_infos

        new_id        date      time
0            0  2014-06-06  21:41:42
1            1  2014-06-06  18:58:53
2            2  2014-06-06  18:52:58
3            3  2014-06-06  16:58:17
4            4  2014-06-06  14:23:44
...        ...         ...       ...
117756  117774  2020-05-16  12:21:35
117757  117775  2020-05-16  12:19:20
117758  117776  2020-05-16  12:18:09
117759  117777  2020-05-16  12:17:54
117760  117778  2020-05-16  12:16:49

[117761 rows x 3 columns]

In [7]:
df_combined = df_infos.merge(df_annotated, left_on='new_id', right_on='id')
df_combined = df_combined.drop(columns=['new_id'])
df_combined

,date,time,id,tekst,wydźwięk,klucze,wyzywanie,grożenie,wykluczanie,odczłowieczanie,...,stygmatyzacja,szantaż,inne,ksenofobia,szowinizm,rasizm,seksizm,antysemityzm,homofobia,inne.1
0,2014-06-06,21:41:42,0,Dokładnie! Dlatego trzeba komuchów gonić przed sądy póki żyją. I mięć otwarte oczy na komuchów zakamuflowanych...,-1,komuchów; gonić komuchów,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014-06-06,18:58:53,1,Polska Polityka: Sądy bardziej bezkarne niż w PRL …,-1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-06-06,18:52:58,2,Sienkiewicz: Odbieramy prawo jazdy bałwanom. Korzystamy z tego pełną gębą! Strączyński - sądy pękną! #.U5Hxyi0nBkk.twitter …,-1,odbierajmy [...] bałwanom,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014-06-06,16:58:17,3,Policjanci hurtowo odbierają prawa jazdy. A sądy często je zwracają,-1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014-06-06,14:23:44,4,"Żale Nałęcza i riposta Macierewicza: Pan był w par­tii ko­mu­ni­stycz­nej, czy ma prawo wy­gła­szać takie sądy?",0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15197,2016-11-12,22:28:20,16308,"Odpowiedziałem, że z powodu #ryzyko #odpZaWadliwySkład #TK ... #ktoZaToZapłaci, gdy #sądy i #ETPC podzielą wątpliwości?",0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15198,2016-11-12,21:15:01,16309,"PiS lubi PRL. Szkoła jak w PRL, Sejm - władzą najwyższą, sądy ludowe, prokurator stanu wojennego.. to i jednostki Ludowego Wojska Polskiego! …",-1,PiS lubi PRL,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15199,2016-11-12,15:43:14,16310,Przed SN pojawiaja sie nowe historie #sady #IIIRP pic.twitter.com/xsVIb1tViP,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15200,2016-11-12,11:30:36,16311,"Gdyby były sądy, a nie są. Wtedy tak, ale...i tak większość spraw zgodnych z prawem. Paradoks.",0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15201,2016-11-12,08:59:37,16312,"'''REZERWĘ'' się w rachunkowości zawiązuje na roszczenia, odszkodowania... Czyli jeszcze może ich ''jeb**ć'' jak sądy pracy zdecydują'",-1,jeszcze można ich jebać [...] sądy pracy zdecydują,NaN,1.0,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Yearly counts analysis
---

In [8]:
dates = df_combined['date']
dates.values

array(['2014-06-06', '2014-06-06', '2014-06-06', ..., '2016-11-12',
       '2016-11-12', '2016-11-12'], dtype=object)

In [9]:
years = np.array([d.split('-')[0] for d in dates.values])
years

array(['2014', '2014', '2014', ..., '2016', '2016', '2016'], dtype='<U4')

In [10]:
np.unique(years, return_counts=True)

(array(['2014', '2015', '2016'], dtype='<U4'), array([2286, 6676, 6240]))